<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Report;
use Illuminate\Support\Facades\DB;

class ReportController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $user = $request->user();
        $query = Report::with(['hospital', 'user']);

        // Context-driven row-level data isolation
        if ($user->role === 'hospital_admin') {
            $query->where('hospital_id', $user->hospital_id);
        } elseif ($user->role !== 'system_admin') {
            abort(403, 'Unauthorized access to reporting logs.');
        }

        return response()->json($query->latest()->get());
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $user = $request->user();

        // Enforce backend parameters over user inputs to prevent boundary cross-posting
        if ($user->role === 'hospital_admin') {
            $request->merge(['hospital_id' => $user->hospital_id]);
        }

        // Always bind the generator to the actual authenticated actor session
        $request->merge(['generated_by' => $user->id]);

        $validated = $request->validate([
            'hospital_id' => 'required|exists:hospitals,id',
            'generated_by' => 'required|exists:users,id',
            'period_start' => 'required|date',
            'period_end' => 'required|date',
        ]);

        $hospitalId = $validated['hospital_id'];

        // 1. Trace assets back to the hospital by joining through the wards table
        $totalResources = DB::table('resources')
            ->join('wards', 'resources.ward_id', '=', 'wards.id')
            ->where('wards.hospital_id', $hospitalId)
            ->count();

        $statusCounts = DB::table('resources')
            ->join('wards', 'resources.ward_id', '=', 'wards.id')
            ->where('wards.hospital_id', $hospitalId)
            ->select('resources.status', DB::raw('count(*) as total'))
            ->groupBy('resources.status')
            ->pluck('total', 'status')
            ->all();

        // 2. Fetch comments via resources linked to wards belonging to this facility
        $comments = DB::table('comments')
            ->join('resources', 'comments.resource_id', '=', 'resources.id')
            ->join('wards', 'resources.ward_id', '=', 'wards.id')
            ->where('wards.hospital_id', $hospitalId)
            ->whereBetween('comments.created_at', [$validated['period_start'] . ' 00:00:00', $validated['period_end'] . ' 23:59:59'])
            ->select('comments.*', 'resources.name as resource_name')
            ->latest('comments.created_at')
            ->get();

        $available = $statusCounts['available'] ?? 0;
        $occupied = $statusCounts['occupied'] ?? 0;
        $maintenance = $statusCounts['maintenance'] ?? 0;
        $decommissioned = $statusCounts['decommissioned'] ?? 0;

        // 3. Compile structural text framework with live indicators
        $content = "============================================================\n";
        $content .= "FACILITY RESOURCE ACCOUNTABILITY REPORT\n";
        $content .= "============================================================\n";
        $content .= "Facility Scope ID : #" . $hospitalId . "\n";
        $content .= "Generated By      : " . ($user->name ?? 'Admin Session') . " (ID: #" . $user->id . ")\n";
        $content .= "Generation Time   : " . now()->toDateTimeString() . "\n";
        $content .= "Reporting Window  : " . $validated['period_start'] . " to " . $validated['period_end'] . "\n\n";

        $content .= "------------------------------------------------------------\n";
        $content .= "1. CURRENT RESOURCE INSTANCE CAPACITIES\n";
        $content .= "------------------------------------------------------------\n";
        $content .= "Total Tracked Assets : " . $totalResources . "\n";
        $content .= " - Available         : " . $available . "\n";
        $content .= " - Occupied          : " . $occupied . "\n";
        $content .= " - In Maintenance    : " . $maintenance . "\n";
        $content .= " - Decommissioned    : " . $decommissioned . "\n\n";

        $content .= "------------------------------------------------------------\n";
        $content .= "2. OPERATIONAL WARD LOGS & INCIDENT FEED\n";
        $content .= "------------------------------------------------------------\n";

        if ($comments->isEmpty()) {
            $content .= "No condition log entries or shift updates posted during this specific interval.\n";
        } else {
            foreach ($comments as $comment) {
                $content .= "[" . $comment->created_at . "] Asset: " . $comment->resource_name . "\n";
                $content .= " Log entry: " . $comment->content . "\n";
                $content .= " --------------------------------------------------------\n";
            }
        }

        // Overwrite payload content with the processed data stream
        $validated['content'] = $content;
        $validated['generated_at'] = now();

        $report = Report::create($validated);

        // Load relations before response so frontend updates gracefully
        $report->load(['hospital', 'user']);

        return response()->json([
            'message' => 'Report compiled successfully from live metrics',
            'data' => $report
        ], 201);
    }

    /**
     * Display the specified resource.
     */
    public function show(Request $request, string $id)
    {
        $user = $request->user();
        $report = Report::with(['hospital', 'user'])->findOrFail($id);

        if ($user->role === 'hospital_admin' && $report->hospital_id !== $user->hospital_id) {
            abort(403, 'Unauthorized access to this document framework.');
        }

        return response()->json($report);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $user = $request->user();
        $report = Report::findOrFail($id);

        if ($user->role === 'hospital_admin' && $report->hospital_id !== $user->hospital_id) {
            abort(403, 'Unauthorized modification context.');
        }

        $validated = $request->validate([
            'content' => 'sometimes|string'
        ]);

        $report->update($validated);

        return response()->json([
            'message' => 'Report updated successfully',
            'data' => $report
        ]);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Request $request, string $id)
    {
        $user = $request->user();
        $report = Report::findOrFail($id);

        if ($user->role === 'hospital_admin' && $report->hospital_id !== $user->hospital_id) {
            abort(403, 'Unauthorized deletion privileges.');
        }

        $report->delete();

        return response()->json([
            'message' => 'Report deleted successfully'
        ]);
    }
}
